Repository ClassicPress-plugins/classic-commerce, pull requests merged in 2019-10, with the labels that each got.

#41 Change admin status tools page
  includes/api/v2/class-wc-rest-system-status-tools-v2-controller.php
Labels: In Progress

#39 Update email settings page
  includes/admin/settings/class-wc-settings-emails.php
Labels: In Progress

#49 Change WC to CC in menus and page titles
  includes/admin/class-wc-admin-menus.php
Labels: Good for Merge

#35 Change admin footer text to Classic Commerce
  includes/admin/class-wc-admin.php
Labels: In Progress, question

#40 Fix admin help screen
  includes/admin/class-wc-admin-help.php
Labels: In Progress

#28 Add contributions steps
  README.md
Labels: Good for Merge

#34 Fix Build Processes
  .travis.yml
  tests/bin/install.sh
  tests/bin/phpcs.sh
  tests/bin/phpunit.sh
  tests/bin/run-e2e-CI.sh
  tests/bin/travis.sh
Labels: In Progress

#62 Fix remaining text-domains
  i18n/languages/woocommerce.pot
  includes/admin/class-wc-admin-menus.php
  includes/admin/settings/class-wc-settings-emails.php
  includes/class-wc-cart-session.php
  includes/class-wc-checkout.php
  includes/customizer/class-wc-shop-customizer.php
  includes/data-stores/class-wc-data-store-wp.php
  includes/log-handlers/class-wc-log-handler-email.php
Labels: In Progress, help wanted

#47 Simplify extensions page
  includes/admin/class-wc-admin-addons.php
  includes/admin/helper/views/html-section-account.php
  includes/admin/helper/views/html-section-nav.php
  includes/admin/views/html-admin-page-addons.php
Labels: Good for Merge, question

#38 Change status report for Classic Commerce
  includes/admin/views/html-admin-page-status-report.php
Labels: Good for Merge, question

#80 Fix broken checks for supported themes
  includes/class-woocommerce.php
Labels: bug-fix

#30 Remove Jetpack + WooCommerce services Installation
  includes/admin/class-wc-admin-setup-wizard.php
  includes/class-wc-install.php
  tests/unit-tests/setup/functions.php
Labels: In Progress, help wanted
