Repository ClassicPress-plugins/classic-commerce, pull requests merged in 2020-01, with the labels that each got.

#171 Change compat plugin warning message
  includes/admin/views/html-notice-require-compat-plugin.php
Labels: Good for Merge, enhancement

#170 Run Travis CI against all PRs and branches again
  .travis.yml
Labels: Good for Merge

#169 Fix for theme template directory issue #167
  includes/class-woocommerce.php
Labels: Good for Merge

#168 Fix deactivating wc/cc problem
  classic-commerce.php
Labels: Good for Merge

#173 Further improvements to CC/Woo activation logic
  classic-commerce.php
Labels: Good for Merge, bug-fix

#175 Fix a fatal error when CC is active and the user tries to activate Woo
  classic-commerce.php
Labels: Good for Merge

#177 Fix for CC admin menu icon display issues
  includes/class-woocommerce.php
Labels: bug-fix

#166 Add usage tracking opt out
  includes/admin/settings/class-wc-settings-accounts.php
  includes/class-wc-update-client.php
Labels: enhancement
